language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

env:
  - NODE_ENV: development
    SCRIPT: lint
  - NODE_ENV: development
    SCRIPT: test
  - NODE_ENV: production
    SCRIPT: build

script: yarn run ${SCRIPT}
